name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core
  - jupyterlite-xeus
  - jupyterlite-pyodide-kernel
  # - jupyterlab-lsp
  # - jupyterlab-git==0.30.0
