name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  # Kernals
  - xeus-python
  # Packages
  - numpy
  - scipy
  - sympy
  - matplotlib
  # - jedi-language-server
